name = "Mjolnir"
uuid = "1154507a-7ac2-44fe-9f15-34617bca9db5"
authors = ["Mike J Innes <mike.j.innes@gmail.com>"]
version = "0.2.0"

[deps]
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
IRTools = "0.4"
MacroTools = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
